### ISSUE TITLE
Not sure what changed in this project

### ISSUE THREAD

**Issue by Karyum** [WebAhead8/PS4Games#14]
other than css and more html what really changed ? 
Heres is the project's README, read the first goal https://github.com/WebAhead/master-reference/blob/master/coursebook/week-6/alternate-project.md

> use atleast 1 API to fetch data from the server.

There is no data being fetched from the server.

**Comment by Jhdbna** [comment]
what do you mean by fetching data from the server ?
except the html and css updates we did a new fetch that shows the details of the selected result(game) .

**Comment by Jhdbna** [comment]
we will update it in next week project  .
